/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paintball.interfaz;

/**
 *
 * @author alvaro
 */
public class Campo extends javax.swing.JFrame {

    /**
     * Creates new form Campo
     */
    public Campo() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogequipamiento = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        botonequipamientoc = new javax.swing.JButton();
        botoninicioc2 = new javax.swing.JButton();
        botonsalirc2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcantidadjugadoresc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botonreservac = new javax.swing.JButton();
        botonsalirc = new javax.swing.JButton();
        Combotipocampo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txttotalc = new javax.swing.JTextField();
        txtpreciohorac = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtlimitejugadores = new javax.swing.JTextField();
        botoninicio1 = new javax.swing.JButton();

        jDialogequipamiento.setMinimumSize(new java.awt.Dimension(390, 180));

        jLabel8.setText("¿QUIERES RESERVAR EQUIPAMIENTO?");

        botonequipamientoc.setText("RESERVAR EQUIPAMIENTO");

        botoninicioc2.setText("INICIO");

        botonsalirc2.setText("SALIR");

        javax.swing.GroupLayout jDialogequipamientoLayout = new javax.swing.GroupLayout(jDialogequipamiento.getContentPane());
        jDialogequipamiento.getContentPane().setLayout(jDialogequipamientoLayout);
        jDialogequipamientoLayout.setHorizontalGroup(
            jDialogequipamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogequipamientoLayout.createSequentialGroup()
                .addGroup(jDialogequipamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogequipamientoLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(botonequipamientoc))
                    .addGroup(jDialogequipamientoLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jDialogequipamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDialogequipamientoLayout.createSequentialGroup()
                                .addComponent(botoninicioc2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonsalirc2))
                            .addComponent(jLabel8))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jDialogequipamientoLayout.setVerticalGroup(
            jDialogequipamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogequipamientoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonequipamientoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jDialogequipamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoninicioc2)
                    .addComponent(botonsalirc2))
                .addGap(52, 52, 52))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fecha de inicio de reserva:");

        jLabel2.setText("Fecha de Fin de reserva :");

        txtcantidadjugadoresc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadjugadorescActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad de Participantes :");

        botonreservac.setText("Reservar");
        botonreservac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonreservacActionPerformed(evt);
            }
        });

        botonsalirc.setText("Salir");
        botonsalirc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsalircActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo de campo:");

        jLabel5.setText("Precio hora: ");

        jLabel6.setText("Precio Total:");

        txttotalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalcActionPerformed(evt);
            }
        });

        txtpreciohorac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreciohoracActionPerformed(evt);
            }
        });

        jLabel7.setText("Limite de jugadores que podeis ir :");

        txtlimitejugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlimitejugadoresActionPerformed(evt);
            }
        });

        botoninicio1.setText("INICIO");
        botoninicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoninicio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtcantidadjugadoresc, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txttotalc, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Combotipocampo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtpreciohorac, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonreservac)
                                .addGap(18, 18, 18)
                                .addComponent(botonsalirc)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtlimitejugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(botoninicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(Combotipocampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtpreciohorac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcantidadjugadoresc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txttotalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonreservac)
                    .addComponent(botonsalirc)
                    .addComponent(jLabel7)
                    .addComponent(txtlimitejugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(botoninicio1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcantidadjugadorescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadjugadorescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadjugadorescActionPerformed

    private void botonreservacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonreservacActionPerformed

            jDialogequipamiento.setVisible(true);
       jDialogequipamiento.setLocationRelativeTo(this);


        // TODO add your handling code here:
    }//GEN-LAST:event_botonreservacActionPerformed

    private void botonsalircActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsalircActionPerformed

        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_botonsalircActionPerformed

    private void txttotalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalcActionPerformed

    private void txtpreciohoracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreciohoracActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreciohoracActionPerformed

    private void txtlimitejugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlimitejugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlimitejugadoresActionPerformed

    private void botoninicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoninicio1ActionPerformed

        this.setVisible(false);
        Login log = new Login();
        log.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_botoninicio1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Campo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Campo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Campo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Campo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Campo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combotipocampo;
    private javax.swing.JButton botonequipamientoc;
    private javax.swing.JButton botoninicio1;
    private javax.swing.JButton botoninicioc2;
    private javax.swing.JButton botonreservac;
    private javax.swing.JButton botonsalirc;
    private javax.swing.JButton botonsalirc2;
    private javax.swing.JDialog jDialogequipamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtcantidadjugadoresc;
    private javax.swing.JTextField txtlimitejugadores;
    private javax.swing.JTextField txtpreciohorac;
    private javax.swing.JTextField txttotalc;
    // End of variables declaration//GEN-END:variables
}
